default: &default_settings
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5

development:
  <<: *default_settings
  database: funpachin_development
  host: localhost

production:
  <<: *default_settings
  database: funpachin_production
